inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
  - 'bin/*'
  - 'db/schema.rb'
  - 'node_modules/**/*'
  - 'tmp/**/*'
  - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 150